version: 1
disable_existing_loggers: false

# (참고) 경로와 프로젝트명은 .env에서 설정합니다.
#   PROJECT_NAME=myproject
#   SERVICE_LOG_PATH=/var/log/myproject/service.log
#   AUDIT_LOG_PATH=/var/log/myproject/audit.log

formatters:
  simple:
    format: '[%(asctime)s] [%(levelname)s] %(name)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s", "pathname": "%(pathname)s", "lineno": %(lineno)d, "funcName": "%(funcName)s"}'
    datefmt: '%Y-%m-%dT%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: NOTSET
    formatter: simple
    stream: ext://sys.stdout

  service_file:
    class: logging.FileHandler
    level: NOTSET
    formatter: json
    filename: ${SERVICE_LOG_PATH}
    encoding: utf-8
    delay: true

  audit_file:
    class: logging.FileHandler
    level: NOTSET
    formatter: json
    filename: ${AUDIT_LOG_PATH}
    encoding: utf-8
    delay: true

root:
  level: INFO
  handlers: [console, service_file]

loggers:
  ${PROJECT_NAME}:
    level: INFO
    propagate: true   # 콘솔/서비스 로그는 루트 핸들러로 전달

  # 개인정보보호정책: audit_log는 전용 파일에만 기록, 절대 stdout에 출력하지 않음
  audit:
    level: INFO
    handlers: [audit_file]
    propagate: false
